fix(tsconfig): Extend and remove types issue
The build was failing with the message:

error TS2688: Cannot find type definition file for 'node'.
   The file is in the program because:
        Entry point of type library 'node' specified in compilerOptions

because the core/tsconfig had the `types` field added to it improperly